package co.udea.airline.api.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class OAuth2LoginRequestDTO {
    @NotBlank
    @Schema(description = "The id token generated by google")
    String idToken;
}
