CREATE TABLE PERSON (
    PERSON_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_IDENTIFICATION_TYPE INT NOT NULL,
    IDENTIFICATION_NUMBER VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    GENRE CHAR(1),
    BIRTH_DATE DATE,
    PHONE_NUMBER VARCHAR(255),
    COUNTRY VARCHAR(255),
    PROVINCE VARCHAR(255),
    CITY VARCHAR(255),
    RESIDENCE VARCHAR(255),
    EMAIL VARCHAR(255),
    ACCESS_KEY VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_IDENTIFICATION_TYPE) REFERENCES IDENTIFICATIONTYPE(IDENTIFICATION_TYPE_ID)
);

CREATE TABLE IDENTIFICATIONTYPE (
    IDENTIFICATION_TYPE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IDENTIFICATION_TYPE VARCHAR(255) NOT NULL
);

CREATE TABLE PERSONPOSITION (
    PERSON_POSITION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PERSON_ID NUMBER,
    POSITION_ID NUMBER,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID),
    FOREIGN KEY (POSITION_ID) REFERENCES POSITION(POSITION_ID)
);

CREATE TABLE POSITION (
    POSITION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POSITION_NAME VARCHAR(255),
    DETAIL VARCHAR(255)
);

CREATE TABLE POSITIONPRIVILEGE (
    POSITION_PRIVILEGE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POSITION_ID NUMBER,
    PRIVILEGE_ID NUMBER,
    FOREIGN KEY (POSITION_ID) REFERENCES POSITION(POSITION_ID),
    FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGE(PRIVILEGE_ID)
);

CREATE TABLE PRIVILEGE (
    PRIVILEGE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRIVILEGE_NAME VARCHAR(255),
    DETAIL VARCHAR(255)
);
INSERT INTO POSITION (POSITION_NAME, DETAIL)
VALUES ('USER', 'Regular user role');
SELECT * FROM POSITION;
